version: "3.8"
services:
  nodeserver:
    working_dir: /usr/src/app
    build: ./app
    ports:
      - "4000:3000"
    env_file: ./app/.env
    volumes:
      - ./app:/usr/src/app
    restart: always
  mongo:
    image: mongo
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - ./mongodb:/data/db
